language: r
cache: packages

r_github_packages:
  - jimhester/lintr
  
os:
 - linux
 - osx

after_script:
 - ./travis-tool.sh dump_logs_by_extension "timings"
 - ./travis-tool.sh dump_sysinfo
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'lintr::lint_package()'
